add a script to read a register multiple times
cms-gem-daq-project/reg_utils pull request #33
Opened 2018-09-19 15:54 UTC by AndrewLevin

This script first issues a link reset, then reads a register, whose name is an input parameter, n times, where n is also an input parameter.

## Description
This script takes three mandatory input parameters: the name of the register to read, the number of times to read the register, and the sleep delay between the reads. There is also an optional output filename parameter. 

The script first issues a link reset, then performs the repeated reads, then reports the register values in the form of a python dictionary. Six slow control monitoring registers are also read at the beginning at the end, and their values, and the difference between their initial and final values, is reported in the form of a table.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context
We are trying to investigate an issue of bit slip i.e. a register which should contain a constant does not have a constant value based on tests using gem_reg.py

## How Has This Been Tested?
This script has been tested both on gem904qc8daq and on the ctp7 (use on the ctp7 requires commenting and uncommenting some of the import lines).

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-09-24 07:12 UTC, bdorney commented on python/reg_interface/scripts/repeated_reg_read.py
> +    #readAddress()
What is the purpose of these commented code blocks?  Typically we should avoid pushing code with large commented sections into the central repo.

2018-09-24 07:13 UTC, bdorney commented on python/reg_interface/scripts/repeated_reg_read.py
> +    time.sleep(float(sys.argv[3])/float(1000000))
Why are you using `sys.argv` container when you have created an `OptionParser()` instance?

2018-09-24 07:14 UTC, bdorney commented on python/reg_interface/scripts/repeated_reg_read.py
> +    from optparse import OptionParser
We have typically are more in favour of the `ArgParse` module for option parsing, see [Jared's comment](https://github.com/cms-gem-daq-project/reg_utils/pull/22#issuecomment-404862393) for some examples.

2018-09-24 07:15 UTC, bdorney commented on python/reg_interface/scripts/repeated_reg_read.py
> +       rpc_connect("eagle26")
Why have you hard coated a CTP7 alias here?  The project has 12 CTP7's.  By hardcoding a specific alias this code will only work on one of them.

2018-09-24 07:20 UTC, bdorney commented on python/reg_interface/scripts/repeated_reg_read.py
> +    print >> f, "| before | "+crc_error_cnt_before+"    | "+packet_error_cnt_before+"       | "+bitstuffing_error_cnt_before+"            | "+timeout_error_cnt_before+"        | "+axi_strobe_error_cn
I don't have the link handy, but we typically prefer using `format` instead of string concatenation.  e.g.

```python
 print("| before | {0}  | {1} | {2} | {3} | {4} | {5} |".format(
   crc_error_cnt_before,
   packet_error_cnt_before,
   bitstuffing_error_cnt_before,
   timeout_error_cnt_before,
   axi_strobe_error_cnt_before,
   transaction_cnt_before
))
```

Additionally unnecessary white space should be avoided.

Also use a file object to write this too and also print to the screen.  Please keep your print statements compatible with python 2 & 3, not only python 2.

# python 2.X only
```python
print "some text"
```

# python 2 & 3 compatible
```python
print("some text")
```

2018-09-24 07:22 UTC, bdorney commented on python/reg_interface/scripts/repeated_reg_read.py
> +    d = {}
please use more description variable names, e.g. not one letter.

2018-09-24 07:23 UTC, bdorney requested changes
Improvements to code quality are needed.

2018-09-24 07:24 UTC, bdorney commented
> (use on the ctp7 requires commenting and uncommenting some of the import lines).

We will be moving to an rpm based installation on the CTP7's but this will require an updated linux image from the card makers.  For this please drop the lines that need to be commented when pushing to the official repo.

2018-09-24 07:24 UTC, bdorney commented
Could you please add the help menu printout and some usage examples to the PR description.

2018-09-24 07:28 UTC, bdorney commented on python/reg_interface/scripts/repeated_reg_read.py
> +from reg_utils.reg_interface.common.jtag import initJtagRegAddrs
remove unnecessary imports.

2018-09-24 09:09 UTC, AndrewLevin commented
@bdorney, I have made all of the requested updates, other than https://github.com/cms-gem-daq-project/reg_utils/pull/33#issuecomment-423893577.  Regarding https://github.com/cms-gem-daq-project/reg_utils/pull/33#issuecomment-423893577, it seems the import statements for running on ctp7 and DAQ PC are mutually exclusive. Please clarify what you want.

2018-09-24 09:37 UTC, bdorney commented
> @bdorney, I have made all of the requested updates, other than #33 (comment). Regarding #33 (comment), it seems the import statements for running on ctp7 and DAQ PC are mutually exclusive. Please clarify what you want.

This code generates an rpm that is installed on a machine.  Right now these are installed on the DAQ machine.  In the future the linux image of the CTP7 will be updated such that rpm's can be installed on each boot of the OS (if the card is rebooted or power cycled only things under `/mnt/persistent/` persist through reboot...everything is reloaded from an image on the card.  

So in this future linux image scenario, there will be no commenting/uncommenting import lines.  The package is installed and it works out of the box.  Please update to reflect this.  For testing purposes now you needed the lines, but in the repo don't push them.

2018-09-24 11:54 UTC, AndrewLevin commented
So, is it correct that these lines

```
from reg_utils.reg_interface.common.reg_xml_parser import getNode, parseXML
from reg_utils.reg_interface.common.print_utils import printRed
from reg_utils.reg_interface.common.jtag import initJtagRegAddrs
from reg_utils.reg_interface.common.reg_base_ops import *
```

will work on the ctp7 in the future, so these lines

```
#from rw_reg import *                                                                                                                                                                     
#from mcs import *   
```

can be removed?

2018-09-24 11:55 UTC, bdorney commented
That is correct.

2018-09-24 12:03 UTC, AndrewLevin commented
OK, the commented import lines are removed now.

2018-09-24 12:08 UTC, bdorney submitted a review, later dismissed

2018-11-07 16:46 UTC, jsturdy reviewed
Comments on design choices

2018-11-07 16:46 UTC, jsturdy commented on python/reg_interface/scripts/repeated_reg_read.py
> +
Why are `nreads` and `sleeptime` of type `str`?
In your usage you're casting them anyway, why not just let the option parser do that for you?

2018-11-07 16:46 UTC, jsturdy commented on python/reg_interface/scripts/repeated_reg_read.py
> +    time.sleep(float(args.sleeptime)/float(1000000))
Why are you doing `float(1000000)`, instead of just `1000000.`? (also in L86)

2018-11-07 16:46 UTC, jsturdy commented on python/reg_interface/scripts/repeated_reg_read.py
> +    transaction_cnt_delta = str(int(transaction_cnt_after,16) - int(transaction_cnt_before,16))
Why are you doing `str(int(value,base))`?
In the format string you can control this anyway, are you worried about the return type of `readAddress`?

2018-11-07 16:46 UTC, jsturdy commented on python/reg_interface/scripts/repeated_reg_read.py
> +         ))
For all of your `write`/`print` calls, you could reduce the duplication you have here by just creating a string of the thing you're going to `write`/`print`, and then just calling, e.g., 
```python
outstring = "blah".format(values)
f.write(outstring)
print(outstring)
```

2018-11-07 16:46 UTC, jsturdy commented on python/reg_interface/scripts/repeated_reg_read.py
> +from reg_utils.reg_interface.common.jtag import initJtagRegAddrs
seems unneeded

2018-11-07 16:46 UTC, jsturdy commented on python/reg_interface/scripts/repeated_reg_read.py
> +from reg_utils.reg_interface.common.print_utils import printRed
seems unneeded

2018-11-07 16:46 UTC, jsturdy commented on python/reg_interface/scripts/repeated_reg_read.py
> +import argparse
probably only need this inside `__main__`

2018-11-12 09:27 UTC, AndrewLevin commented on python/reg_interface/scripts/repeated_reg_read.py
> +import argparse
the import statements are moved now

2018-11-12 09:27 UTC, AndrewLevin commented on python/reg_interface/scripts/repeated_reg_read.py
> +from reg_utils.reg_interface.common.print_utils import printRed
removed

2018-11-12 09:27 UTC, AndrewLevin commented on python/reg_interface/scripts/repeated_reg_read.py
> +from reg_utils.reg_interface.common.jtag import initJtagRegAddrs
removed

2018-11-12 09:27 UTC, AndrewLevin commented on python/reg_interface/scripts/repeated_reg_read.py
> +         ))
changed

2018-11-12 09:28 UTC, AndrewLevin commented on python/reg_interface/scripts/repeated_reg_read.py
> +    transaction_cnt_delta = str(int(transaction_cnt_after,16) - int(transaction_cnt_before,16))
str(...) is removed now

2018-11-12 09:28 UTC, AndrewLevin commented on python/reg_interface/scripts/repeated_reg_read.py
> +    time.sleep(float(args.sleeptime)/float(1000000))
changed in both places

2018-11-12 09:28 UTC, AndrewLevin commented on python/reg_interface/scripts/repeated_reg_read.py
> +
changed

2018-11-12 09:28 UTC, AndrewLevin commented
@jsturdy, I have addressed all of your comments now

2018-11-12 10:21 UTC, jsturdy reviewed
My point with the comment on the `str(int(value,base))` was really what does `readAddress` return, i.e., is `int(value,16)` necessary: is `value` a `str` type representing a hexadecimal value?
If not, and you want to `print` it as `dec/hex` representation, you can control that in the format string (`{:d}` or `{:x}`), assuming the return type of `readAddress` is an integer type (regardless of representation)

2018-11-12 10:31 UTC, AndrewLevin commented
@jsturdy, `readAddress` returns an object of type `str` representing a hexadecimal value

2018-11-12 11:33 UTC, bdorney commented
Side comment, are you casting these as 16 bit integers?  Are you sure that's correct?  The CTP7 (and the rpc framework) return always 32 bit integers; you can of course drop the higher bits but only in the case that the higher bits are not used.  

Do these counters that the value you're casting as 16 bit integers only use 16 bits?

2018-11-12 12:10 UTC, AndrewLevin commented
@bdorney, the syntax `int(XXX,16)` will create an integer with as many bits necessary:

```
[gemuser@gem904daq01 ~]$ python
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> int('0x1000',16)
4096
>>> int('0x10000',16)
65536
>>> int('0x1000000000000',16)
281474976710656
>>> 
```

2018-11-12 12:22 UTC, bdorney commented
I misread your response, I understand. Thanks for the example. The 16 is the base.

2018-11-12 12:48 UTC, jsturdy approved these changes
> @jsturdy, `readAddress` returns an object of type `str` representing a hexadecimal value

OK, thanks (I guess I'll complain about this elsewhere)

2018-11-12 14:39 UTC, bdorney approved these changes
Cursory approval.  It would be nice to add this to the user's guide under [Common Slow Control Actions](https://github.com/cms-gem-daq-project/sw_utils/blob/develop/v3ElectronicsUserGuide.md#common-slow-control-actions).

2018-11-12 15:03 UTC, merged

2018-11-12 15:37 UTC, AndrewLevin commented
@bdorney, I create a pull request for sw_utils to add this to the v3 user's guide: https://github.com/AndrewLevin/sw_utils/pull/1